require 'xcodeproj'
require 'fileutils'
require 'pathname'

module Badev
  module XCConfig

    extend Badev::Helpers

    def self.collect_xcodeprojs(dirs)
      xcodeprojs = []

      dirs.each do |base|
        if File.exists? base then
          Dir.glob(File.join(base, "**/*.xcodeproj")) do |dir|
            xcodeprojs << File.expand_path(dir)
          end
        end
      end

      xcodeprojs
    end

    def self.collect_xcconfigs(dirs)
      xcconfigs = []

      dirs.each do |base|
        if File.exists? base then
          Dir.glob(File.join(base, "**/*.xcconfig")) do |dir|
            xcconfigs << File.expand_path(dir)
          end
        end
      end

      xcconfigs
    end

    def self.make_xcconfig_line(key, value)
      v = value
      if value.kind_of?(Array) then
        v = value.join(" ")
      end

      "#{key} = #{v}"
    end

    def self.build_default_xcconfig(destname, project, configuration, target, settings_list)
      template = <<-XEND.gsub(/^ {6}/, '')
      //!bagen generate binaryage #{shellescape(project)} #{shellescape(configuration)} #{shellescape(target)} > #{shellescape(destname)}
      //
      // this file should be set as #{configuration} configuration for target #{target} in #{project}.xcodeproj

      // following included file can be regenerated by running 'badev regen_xcconfigs'
      #include "#{destname}"

      // here you can follow with your custom settings overrides if needed
      XEND

      export = ""
      settings_list.each do |settings|
        export += "\n"
        settings.each do |key, value|
          export += "// " + make_xcconfig_line(key, value) + "\n"
        end
      end

      template + export
    end

    def self.init_configs_for_proj(proj, dest)
      basename = File.basename proj.path, ".xcodeproj"

      # create xcconfig file for each configuration-target combination
      proj.build_configurations.each do |conf|
        configuration_settings = conf.build_settings

        proj.targets.each do |target|
          target_settings = target.build_settings(conf.name)

          # TODO: here we should sanitize filenames for bad characters
          filename = File.join(dest, "#{basename}_#{conf.name}_#{target.name}.xcconfig")
          destname = (File.basename filename, ".xcconfig") + "_generated.xcconfig"
          unless File.exists? filename
            content = build_default_xcconfig(destname, basename, conf.name, target.name, [configuration_settings, target_settings])
            File.open(filename, 'w') { |file| file.write(content) }
            relpath = "./"+Pathname.new(filename).relative_path_from(Pathname.new(Dir.pwd)).to_s
            puts "generated: #{relpath.yellow}"
          else
            puts "#{filename.blue} already exists => skipping"
          end
        end
      end
    end

    def self.parse_xcconfig_header(path)
      lines = File.read(path).split("\n")
      return unless lines[0] =~ /\/\/!(.*)/
      generator = $1.strip
    end

    def self.init_configs_in_tree(root_path)
      xcodeprojs = collect_xcodeprojs([root_path])

      xcodeprojs.each do |xcodeproj|
        xcconfig_dir = xcodeproj.gsub(".xcodeproj", ".xcconfigs")
        proj = Xcodeproj::Project.open(xcodeproj)
        FileUtils.mkdir_p xcconfig_dir
        init_configs_for_proj(proj, xcconfig_dir)
      end
    end

    def self.regen_configs_in_tree(root_path)
      xcconfigs = collect_xcconfigs([root_path])
      lastdir = nil
      xcconfigs.each do |xcconfig|
        generator = parse_xcconfig_header(xcconfig)
        next unless generator

        dir = File.dirname(xcconfig)
        Dir.chdir dir do
          puts "in #{dir.blue}:" if lastdir!=dir
          lastdir = dir
          sys(generator)
        end
      end
    end

  end
end
